//go:build linux
// +build linux

// Code generated by stringer. DO NOT EDIT.
package p

//go:generate stringer -type Status
type Status int

//nolint:unused
func value() {}

/*line generated.go:12*/
func generatedValue() {}
