package analyzers

import (
	"strings"
	"testing"
)

const allowedCommentSource = `package p
// HUMAN: The provider requires ordered retries.
// Reordering these calls breaks failover.
func first() {}

// Retry behavior is tracked in ENG-482.
func second() {}

/*
 * Preserve this behavior.
 * @owned
 */
func third() {}
`

func TestNoUnmatchedCommentsReportsContiguousCommentOnce(t *testing.T) {
	source := `package p
// Explain the operation.
// Keep these steps ordered.
func value() {}
`

	analyzer := analyzerByRule(t, "no-unmatched-comments")
	diagnostics := runAnalyzer(t, analyzer, "p.go", source)
	requireDiagnosticsCount(t, diagnostics, 1)
	requireDiagnostic(t, diagnostics, "LEG039 no-unmatched-comments")
}

func TestNoUnmatchedCommentsAcceptsConfiguredAllowPaths(t *testing.T) {
	settings := Settings{
		CommentMatchers:          []string{`\beng-\d+\b`},
		CommentPrefixIdentifiers: []string{"human"},
		CommentSuffixIdentifiers: []string{"@OWNED"},
	}

	analyzer := analyzerByRuleWithSettings(t, "no-unmatched-comments", settings)
	diagnostics := runAnalyzer(t, analyzer, "p.go", allowedCommentSource)
	requireDiagnosticsCount(t, diagnostics, 0)
}

func TestNoUnmatchedCommentsRequiresIdentifierBoundaries(t *testing.T) {
	settings := Settings{
		CommentPrefixIdentifiers: []string{"HUMAN"},
		CommentSuffixIdentifiers: []string{"@owned"},
	}
	source := `package p
// HUMANIZED: This is not owned.
func first() {}

// Preserve this behavior. not@owned
func second() {}
`

	analyzer := analyzerByRuleWithSettings(t, "no-unmatched-comments", settings)
	diagnostics := runAnalyzer(t, analyzer, "p.go", source)
	requireDiagnosticsCount(t, diagnostics, 2)
}

func TestNoUnmatchedCommentsIgnoresGoMetadata(t *testing.T) {
	source := `//go:build linux
// +build linux

// Code generated by stringer. DO NOT EDIT.
package p

//go:generate stringer -type Status
type Status int

//nolint
func value() {}
`

	analyzer := analyzerByRule(t, "no-unmatched-comments")
	diagnostics := runAnalyzer(t, analyzer, "p.go", source)
	requireDiagnosticsCount(t, diagnostics, 0)
}

func TestNoUnmatchedCommentsChecksMixedMetadataGroups(t *testing.T) {
	source := `package p
//go:generate stringer -type Status
// Explain the status values.
type Status int
`

	analyzer := analyzerByRule(t, "no-unmatched-comments")
	diagnostics := runAnalyzer(t, analyzer, "p.go", source)
	requireDiagnosticsCount(t, diagnostics, 1)
}

func TestNoUnmatchedCommentsChecksMisplacedGeneratedMarker(t *testing.T) {
	source := `package p
// Code generated by stringer. DO NOT EDIT.
func value() {}
`

	analyzer := analyzerByRule(t, "no-unmatched-comments")
	diagnostics := runAnalyzer(t, analyzer, "p.go", source)
	requireDiagnosticsCount(t, diagnostics, 1)
}

func TestNoUnmatchedCommentsIgnoresCgoPreamble(t *testing.T) {
	source := `package p
/*
#include <stdlib.h>
*/
import "C"
`

	analyzer := analyzerByRule(t, "no-unmatched-comments")
	diagnostics := runAnalyzer(t, analyzer, "p.go", source)
	requireDiagnosticsCount(t, diagnostics, 0)
}

func TestNoUnmatchedCommentsIgnoresInvalidMatchers(t *testing.T) {
	matchers := []string{"["}
	settings := Settings{CommentMatchers: matchers}
	source := `package p
// Explain the operation.
func value() {}
`

	analyzer := analyzerByRuleWithSettings(t, "no-unmatched-comments", settings)
	diagnostics := runAnalyzer(t, analyzer, "p.go", source)
	requireDiagnosticsCount(t, diagnostics, 1)
}

func TestNoAutomatedCommentAttributionReportsSignatures(t *testing.T) {
	source := automatedSignatureSource()
	analyzer := analyzerByRule(t, "no-automated-comment-attribution")
	diagnostics := runAnalyzer(t, analyzer, "p.go", source)
	requireDiagnosticsCount(t, diagnostics, 2)
	requireDiagnostic(t, diagnostics, "LEG040 no-automated-comment-attribution")
}

func automatedSignatureSource() string {
	firstIdentifier := "chat" + "gpt"
	secondIdentifier := "clau" + "de"
	signature := "Generated by " + firstIdentifier
	generatedComment := "// " + signature + "."
	author := "@" + "author " + secondIdentifier
	authorLine := " * " + author
	sourceLines := []string{
		"package p",
		generatedComment,
		"func first() {}",
		"",
		"/*",
		authorLine,
		" */",
		"func second() {}",
	}
	return strings.Join(sourceLines, "\n")
}

func TestNoAutomatedCommentAttributionIgnoresTechnologyReferences(t *testing.T) {
	identifier := "chat" + "gpt"
	author := "@" + "author Jeff"
	request := "Send a request to " + identifier
	sentence := request + "."
	commentPrefix := "// " + sentence
	comment := commentPrefix + " " + author
	sourceLines := []string{"package p", comment, "func value() {}"}
	source := strings.Join(sourceLines, "\n")

	analyzer := analyzerByRule(t, "no-automated-comment-attribution")
	diagnostics := runAnalyzer(t, analyzer, "p.go", source)
	requireDiagnosticsCount(t, diagnostics, 0)
}

func TestNoAutomatedCommentAttributionSupportsCustomIdentifiers(t *testing.T) {
	identifiers := []string{"robot"}
	settings := Settings{AutomatedCommentIdentifiers: identifiers}
	author := "@" + "author robot"
	comment := "// " + author
	sourceLines := []string{"package p", comment, "func value() {}"}
	source := strings.Join(sourceLines, "\n")

	analyzer := analyzerByRuleWithSettings(t, "no-automated-comment-attribution", settings)
	diagnostics := runAnalyzer(t, analyzer, "p.go", source)
	requireDiagnosticsCount(t, diagnostics, 1)
}

func TestNoAutomatedCommentAttributionAllowsEmptyIdentifiers(t *testing.T) {
	identifiers := []string{}
	settings := Settings{AutomatedCommentIdentifiers: identifiers}
	identifier := "chat" + "gpt"
	generatedBy := "Generated by " + identifier
	comment := "// " + generatedBy + "."
	sourceLines := []string{"package p", comment, "func value() {}"}
	source := strings.Join(sourceLines, "\n")

	analyzer := analyzerByRuleWithSettings(t, "no-automated-comment-attribution", settings)
	diagnostics := runAnalyzer(t, analyzer, "p.go", source)
	requireDiagnosticsCount(t, diagnostics, 0)
}

func TestPreferLineCommentsReportsMultilineBlockComment(t *testing.T) {
	source := `package p
/*
Explain the operation.
*/
func value() {}
`

	analyzer := analyzerByRule(t, "prefer-line-comments")
	diagnostics := runAnalyzer(t, analyzer, "p.go", source)
	requireDiagnosticsCount(t, diagnostics, 1)
	requireDiagnostic(t, diagnostics, "LEG041 prefer-line-comments")
}

func TestPreferLineCommentsAllowsSingleLineBlocksAndCgo(t *testing.T) {
	source := `package p
/*
#include <stdlib.h>
*/
import "C"

/* Keep this concise. */
func value() {}
`

	analyzer := analyzerByRule(t, "prefer-line-comments")
	diagnostics := runAnalyzer(t, analyzer, "p.go", source)
	requireDiagnosticsCount(t, diagnostics, 0)
}
